# Generated by Django 4.2.5 on 2023-10-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('rollno', models.IntegerField()),
                ('subject', models.CharField(max_length=1000)),
                ('quiz1', models.IntegerField()),
                ('preend', models.IntegerField()),
                ('endsem', models.IntegerField()),
            ],
        ),
    ]
