# Generated by Django 4.2.5 on 2023-10-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_student_batch_alter_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='predict',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='slow_learner',
            field=models.CharField(default='Fast Learner', max_length=50),
        ),
    ]
