# Generated by Django 4.2.5 on 2023-10-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_student_predict_student_slow_learner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='predict',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
