# Generated by Django 4.2.5 on 2023-10-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_student_mentor_alter_student_endsem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='endsem',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mentor',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='predict',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='preend',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='quiz1',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='quiz2',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='quiz3',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
