# Generated by Django 4.2.5 on 2023-10-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_student_endsem_alter_student_mentor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='predict',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
